TEXT_GAMEOVER  = "I'M SORRY, NO MORE CREDITS TO PLAY";
TEXT_PLAY      = "MASUK";
TEXT_CREDITS   = "";
TEXT_SPIN      = "PUTAR";
TEXT_PLUS      = "+";
TEXT_MIN       = "-";
TEXT_CURRENCY  = "";
 
TEXT_HELP1     = 'JUMLAH KUPON PER TURNOVER';
TEXT_HELP2     = " ";